name: Tests

on:
  push:
  workflow_dispatch:

env:
  AUTORESVER8: 8.0.37-beta
  AUTORESVER11: 11.0.37-beta

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Check out code
        uses: actions/checkout@v4
      - name: Maven Java 23
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: maven-jdk23:latest
          context: maven/
          file: maven/Dockerfile.jdk23
          build-args: |
            AUTORESVER=${{ env.AUTORESVER11 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Maven Java 8 Classpath
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: maven-jdk8-cp:latest
          context: maven/classpath/
          build-args: |
            AUTORESVER=${{ env.AUTORESVER8 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Maven Java 11
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: maven-jdk11:latest
          context: maven/
          file: maven/Dockerfile.jdk11
          build-args: |
            AUTORESVER=${{ env.AUTORESVER11 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Maven Java 17
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: maven-jdk17:latest
          context: maven/
          file: maven/Dockerfile.jdk17
          build-args: |
            AUTORESVER=${{ env.AUTORESVER11 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Maven Java 21
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: maven-jdk21:latest
          context: maven/
          file: maven/Dockerfile.jdk21
          build-args: |
            AUTORESVER=${{ env.AUTORESVER11 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Maven Java 11 with Java 8 lib
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: maven-jdk11:latest
          context: maven/
          file: maven/Dockerfile.jdk11
          build-args: |
            AUTORESVER=${{ env.AUTORESVER8 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Check out code
        uses: actions/checkout@v4
      - name: Gradle Java 8 Classpath
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: gradle-jdk8-cp:latest
          context: gradle/classpath/
          build-args: |
            AUTORESVER=${{ env.AUTORESVER8 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Gradle Java 11 Module
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: gradle-jdk11-module:latest
          context: gradle/module/
          build-args: |
            AUTORESVER=${{ env.AUTORESVER11 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  native:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Check out code
        uses: actions/checkout@v4
      - name: Maven Java 23 GraalVM native application
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: graal:latest
          context: maven/native/
          build-args: |
            AUTORESVER=${{ env.AUTORESVER11 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: shellcheck:latest
          context: scripts
          file: scripts/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
