name: Maven/Java 8 AutoRes/Classpath

on:
  push:
  workflow_dispatch:
    inputs:
      AUTORES8VER:
        default: '8.0.9-alpha'

jobs:
  maven-java8-classpath:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['8']
        jdk: ['temurin'] # 'semeru' 21 not available yet
        lib: ["${{ inputs.AUTORES8VER }}"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: ${{ matrix.jdk }}
          cache: 'maven'
      - name: Test AutoRes ${{ matrix.lib }}
        run: mvn -DAUTORESVER=${{ matrix.lib }} --file maven/java8/classpath/pom.xml --batch-mode clean test
  # maven-classpath:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       version: ['8', '11', '17', '21']
  #       jdk: ['temurin'] # 'semeru' 21 not available yet
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up JDK
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: ${{ matrix.version }}
  #         distribution: ${{ matrix.jdk }}
  #         cache: 'maven'
  #     - name: Test
  #       run: mvn --file maven/java8/classpath/pom.xml --batch-mode clean test
  # maven-module:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       version: ['11', '17', '21']
  #       jdk: ['temurin'] # 'semeru' 21 not available yet
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up JDK
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: ${{ matrix.version }}
  #         distribution: ${{ matrix.jdk }}
  #         cache: 'maven'
  #     - name: Test
  #       run: mvn --file maven/java8/classpath/pom.xml --batch-mode clean test
