name: Tests

on: [push]

env:
  AUTORESVER8: 8.0.9-alpha

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: tester:latest
          context: gradle/classpath/
          build-args: |
            AUTORESVER=$AUTORESVER8
