name: Maven/Java 8 AutoRes/Classpath

on: [push]

jobs:
  maven:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: ['temurin', 'semeru']
        version: ['11', '17']
        lib: ['8.0.9-alpha', '11.0.8-alpha']
        project: ['classpath', 'module']
        include:
          - jdk: 'temurin'
            version: '21'
            lib: '11.0.8-alpha'
            project: 'classpath'
          - jdk: 'temurin'
            version: '8'
            lib: '8.0.9-alpha'
            project: 'classpath'

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: ${{ matrix.jdk }}
          cache: 'maven'
      - name: Test AutoRes ${{ matrix.lib }}
        run: >
          mvn
          -Dmaven.compiler.target=${{ matrix.version }}
          -DAUTORESVER=${{ matrix.lib }}
          --file maven/${{ matrix.project }}/pom.xml
          --batch-mode
          clean test
